name: Build Package

on:
  release:
    types: [published]
    
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # or your target Python version

    - name: Install Hatch and Twine
      run: |
        pip install hatch twine

    - name: Build distributions
      run: hatch build

    - name: Upload distributions
      uses: actions/upload-artifact@v4
      with:
        name: dist-files
        path: dist/*

    - name: Upload distributions to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*

    - name: Publish to TestPyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        twine upload --repository pypi dist/*
